CREATE DATABASE IF NOT EXISTS `python-products-api` /*!40100 DEFAULT CHARACTER SET latin1 */;

use `python-products-api`;

CREATE TABLE IF NOT EXISTS `TB_PRODUCT` (
  `ID` varchar(36) NOT NULL,
  `NAME` varchar(50) NOT NULL,
  `PRICE` float DEFAULT NULL,
  `URL` varchar(120) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `TB_CATEGORY` (
  `NAME` varchar(50) NOT NULL,
  `PRODUCT_ID` varchar(36) NOT NULL,
  PRIMARY KEY (`NAME`,`PRODUCT_ID`),
  KEY `fk_TB_CATEGORY_1_idx` (`PRODUCT_ID`),
  CONSTRAINT `fk_TB_CATEGORY_1` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `TB_PRODUCT` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

